# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_home:
    pattern: /
    defaults: { _controller: KnpCowboyRanchBundle:Ranch:index }

_cow_add:
    pattern: /cow/
    defaults: { _controller: KnpCowboyRanchBundle:Ranch:add }
    requirements: { _method: POST }

_cow_delete:
    pattern: /cow/{id}
    defaults: { _controller: KnpCowboyRanchBundle:Ranch:delete }
    requirements: { _method: DELETE }